# Question 1

In [ ]:
import numpy as np
array= np.arange(2,50)
print(array)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Question 2

In [ ]:
lst1=[int(input()) for  lst1 in range(5)]
print(lst1)

lst2=[int(input())for lst2 in range(5)]
print(lst2)
  

2
4
6
8
10
[2, 4, 6, 8, 10]
1
3
5
7
9
[1, 3, 5, 7, 9]


In [ ]:
from array import array
import numpy as np
 
lst_array=array("i",lst1)
print(lst_array)
 
lst_array2= array("i",lst2)
print(lst_array2)
 
sum= [0]*10
sum= np.concatenate((lst_array,lst_array2))
print("concatenated ",sum)
 
s=np.sort(sum)
print("sorted ",s)

array('i', [2, 4, 6, 8, 10])
array('i', [1, 3, 5, 7, 9])
concatenated  [ 2  4  6  8 10  1  3  5  7  9]
sorted  [ 1  2  3  4  5  6  7  8  9 10]


# QUESTION 3

In [ ]:
 
import numpy as np
 
arr = np.array( [[ 4, 8, 3],
                 [ 7, 6, 5]] )
 
print("No. of dimensions: ",arr.ndim )
 
print("Shape of array: ", arr.shape)
 
print("Size of array: ", arr.size)
 
print("Array stores elements of type: ", arr.dtype)

No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


# QUESTION 4

In [19]:
 
arr_1= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
arr_2d = np.reshape(arr_1, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# QUESTION 5

In [24]:
 import numpy as np
a = np.array((3,9,7))
b = np.array((5,4,6))
 
s=np.hstack((a,b))
print(s)
 
y=np.vstack((a,b))
print(y)

[3 9 7 5 4 6]
[[3 9 7]
 [5 4 6]]


# QUESTION 6

In [18]:
 
import numpy as np 
 
  
 
def unique(lst): 
 
    x = np.array(lst) 
 
    print(np.unique(x)) 
 
      
 
 
list1 = [10, 20, 10, 30, 40, 40] 
 
print("the unique values from 1st list is") 
unique(list1) 
 
  
 
  
 
list2 =[1, 2, 1, 1, 3, 4, 3, 3, 5] 
 
print("\nthe unique values from 2nd list is") 
unique(list2) 
 
item= set(list2) 
print("No of unique items in the list are:", len(item))

the unique values from 1st list is
[10 20 30 40]

the unique values from 2nd list is
[1 2 3 4 5]
No of unique items in the list are: 5
